// @@@SNIPSTART audiobook-project-java-Gradle-build-file
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group 'ttspackage'
version '0.0.1'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = '21'
    targetCompatibility = '21'
}

sourceSets.main.java.srcDirs 'src'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'io.temporal:temporal-spring-boot-starter:1.31.0'
    implementation platform('org.springframework.ai:spring-ai-bom:1.0.3')
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'commons-io:commons-io:2.11.0'
}

bootRun {
    standardOutput = System.out
}
// @@@SNIPEND
